version: 1.0.{build}
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    cd test\Hangfire.RecurringJobExtensions.Tests

    dotnet test
image: Visual Studio 2017